### PR TITLE
Prevent fixture from creating an empty product.

### PR DESCRIPTION
**Pull request by robjstanley**
Unable to create the Magento fixture Notice: Undefined index: sku in vendor/magetest/magento-behat-extension/src/MageTest/MagentoExtension/Fixture/Product.php line 70

### CODE REVIEW

**Comment by vernard** [comment]
+1. I'm new and I could not proceed because of this error.

**Comment by vernard** [comment]
Pull request caused this error. Forgot to inform that I did try his change before posting a comment.

Notice: Undefined variable: fixtureGenerator in vendor/magetest/magento-behat-extension/src/MageTest/MagentoExtension/Context/Magento
Context.php line 183

**Comment by alistairstead** [comment]
Sorry I didn't spot that when I reviewed it. I'm just adding PHPSpec coverage of this error and will push another PR shortly.

**Comment by alistairstead** [comment]
This should be fixed once https://github.com/MageTest/BehatMage/pull/60 is accepted

you-aint-doing-it-right-sir

**Pull request merged**
