### PR TITLE
Extend RawMinkContext rather than MinkContext

### PR DESCRIPTION
**Pull request by mlopes**

### CODE REVIEW

**Comment by jakzal** [comment]
:+1:

**Comment by debo** [comment]
No gif, no merge... I think I added that in the contributor documentation :)

**Comment by mlopes** [comment]
Debo, the gif should be put there by the person approving, not the person
making the PR. ;)

Cheers,
Marco Lopes

**Comment by debo** [comment]
That's never been the policy between me and @alistairstead ;)

**Comment by mlopes** [comment]
jzlkgh4

**Comment by debo** [comment]
img_giphy

**Pull request merged**
