### PR TITLE
Update composer to use latest Behat release - 3.1.0 .json

### PR DESCRIPTION
**Pull request by tikolakin**
Hi there, since Behat 3.0.5 there are really many things have been released so awesome to have them in magento as well 
Thanks

### CODE REVIEW

**Comment by andytson-inviqa** [comment]
this should be ^3.0.15, which means >= 3.0.15 < 4

**Comment by andytson-inviqa** [comment]
@tikolakin why is this closed?

**Comment by andytson-inviqa** [comment]
nvm, I see I had also submitted a PR #90

**Comment by tikolakin** [comment]
@andytson-inviqa , yep, just noticed it and decided to close this one

**Pull request closed without merging**
